server:
  port: 8080
spring:
  application:
    name: gateway-service
    
zuul:
  routes:
    falshcard:
      url: http://localhost:8089/flashcard
    quiz:
      url: http://localhost:8090/quiz   
